const fruits=["mango","apple","orange","plum"];
// console.log(fruits.length);
// console.log(fruits);
// console.log(fruits.toString());
// console.log(fruits.join("   "));
// console.log(fruits.pop());
// console.log(fruits);
// fruits.push("kiwi");
// console.log(fruits);
// // fruits.shift();
// console.log(fruits);
// fruits.unshift("strawberry");
// console.log(fruits);
// const numbers=["1","2","3","4"];
// const all = fruits.concat(numbers);
// console.log(all);
// const set = [[1,0],[2,0],[3,0]];
// const arr = set.flat();
// console.log(arr);
fruits.splice(2,0,"23","45");
console.log(fruits);
// // fruits.splice(0,2);
// // console.log(fruits);
// const rest=fruits.slice(2);
// console.log(rest);